server:
  port: 8082
#  servlet:
#    path: "*.do"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/netctoss?useSSL=true&characterEncoding=utf-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    password: 123456
    username: root
#  resources:
#    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tedu.springbootdemo02.pojo
  configuration:
    map-underscore-to-camel-case: true



logging:
  level:
    com.tedu.springbootdemo02: debug
